feat: add generics to OptionValues
tj/commander.js pull request #1537
Opened 2021-05-29 08:21 UTC by tyankatsu0105

# Pull Request

## Problem

close #1536 

## Solution

TypeScript typings
- add generics to OptionValues
- add default generics to storeOptionsAsProperties and opts method

## ChangeLog

2021-05-29 23:37 UTC, shadowspawn commented
This looks like it is functional, but I want to experiment a bit. I 'm not expert with generics and the current signatures don't give the cues I expect. The `any` looks a bit odd here:

```
opts<T = any>(): OptionValues<T>;
```

Example usage:

```
const options1 = program.opts(); // weakly typed
const options2 = program.opts<MyOptionValues>(); // strongly typed, added by this PR

program.action((options: commander.OptionValue) => {}); // convenience for weakly typed param
```

2021-05-30 00:27 UTC, shadowspawn commented
How about this? The `extends` is a sanity check that the passed type is a hash/dictionary.

```
interface OptionValues {
  [key: string]: any;
}

opts<T extends OptionValues = OptionValues>(): T;
```

2021-05-30 01:09 UTC, tyankatsu0105 commented
Wow. Looks better than my PR.
I take your advice and will change the code.

2021-05-30 01:11 UTC, tyankatsu0105 commented
done
@shadowspawn thanks for your kind advice :)

2021-05-30 01:42 UTC, shadowspawn commented
Oh, even tidier with not needing to specify default. 😄

2021-05-30 01:45 UTC, shadowspawn requested changes
Suggested tests for `index.test-d.ts` with the `// opts` tests.

```
interface MyCheeseOption {
  cheese: string;
}
const myCheeseOption = program.opts<MyCheeseOption>();
expectType<string>(myCheeseOption.cheese);
// @ts-expect-error Check that options strongly typed and does not allow arbitrary properties
expectType<string>(myCheeseOption.foo);
```

2021-05-30 01:52 UTC, shadowspawn commented
The next release will be from `release/8.x` branch, and the typings have had a refactor causing merge conflicts. Might be easiest to make a new branch from `release/8.x` and redo PR (or copy-down and resolve conflicts if you prefer).

2021-05-30 03:28 UTC, shadowspawn approved these changes
LGTM

2021-05-30 03:29 UTC, shadowspawn commented
Reminder to self: don't merge onto `develop` branch

2021-05-30 04:47 UTC, shadowspawn commented
PR moved to #1539

2021-05-30 04:47 UTC, closed without merging