Feature/help command no pre subcommand
tj/commander.js pull request #1956
Opened 2023-08-13 01:49 UTC by aweebit

# Pull Request

## Problem

## Solution

## ChangeLog

2023-08-13 02:02 UTC, aweebit commented
Posted too early by accident, the description is now complete.

2023-08-13 06:13 UTC, shadowspawn commented
I haven't put a lot of thought into this yet, but my first reaction is I am more interested in making it consistent by calling the hook in both cases. Do you want to have a go at that as well? I am imagining a few lines to add the hook before the direct call to the subcommand in `_dispatchHelpCommand`, not a refactor.  Would be a separate competing PR.

I think some people might try using the `preSubcommand` hook to do some lazy setup, and that might affect the help too.

2023-08-13 14:05 UTC, aweebit commented
> I haven't put a lot of thought into this yet, but my first reaction is I am more interested in making it consistent by calling the hook in both cases.

I don't really like this idea for two reasons:

- There is no `Command` instance that would be reasonable to pass to the `preSubcommand` hooks in the second parameter since the help command only exists virtually.
- There would be a discrepancy between this and how the `preAction` hooks are not called when the help option is invoked (and that is a valid comparison because the help option would have to be implemented in the action handler just like the help command would have to be implemented in a subcommand if the convenience shortcuts were not offered by the library).

    ```js
    try {
      const program = new Command()
        .exitOverride()
        .hook('preAction', () => console.log('preAction'))
        .action(() => {});
      program.parse(['--help'], { from: 'user' }); // 'preAction' not logged
    } catch {}

    try {
      const program = new Command()
        .exitOverride()
        .addHelpCommand('help')
        .hook('preSubcommand', () => console.log('preSubcommand'));
      program.parse(['help'], { from: 'user' }); // 'preSubcommand' would be logged
    } catch {}
    ```

2023-08-22 10:44 UTC, shadowspawn requested changes
This has got 5 extra commits, some of which have landed.

Unless you are keen on cherry pick and rebase, I suggest perhaps redo the small relevant commit on the release 12.x branch (I have merged develop into release 12.x today).

https://github.com/tj/commander.js/pull/1956/commits/77828bab8e66948b234354db9ce7b987115efa19

2023-08-25 07:39 UTC, shadowspawn commented
I was thinking about this again today, and leaning towards triggering the hook again!

https://github.com/tj/commander.js/pull/1956#issuecomment-1676245983

2023-08-26 06:34 UTC, shadowspawn commented
Interesting comparison with a "real" help command. I had not considered that model.

I think of the built-in `prog help foo` as equivalent to `prog foo --help`. I'm leaning towards calling `preSubcommand`, as it did before #1864.

(This is pretty obscure behaviour, no one may ever notice!)

2023-08-26 06:34 UTC, closed without merging