Allow bypassing negation
tj/commander.js pull request #2238
Opened 2024-08-27 19:14 UTC by bernard-wagner

# Pull Request

## Problem

Sometimes it is desired to have an option starting with `--no` to be treated as a regular boolean argument. I encountered this when writing a wrapper for another command and needing to pass the options as is to the sub-process.

## Solution

Since `negate` will be `true` for any option starting with `--no`, the default behavior can be overridden by explicitly changing `negate` to `false`.

2024-08-27 20:52 UTC, shadowspawn commented
There have been some requests whether it is possible to disable the negate support: #1100 #2068

2024-08-30 05:31 UTC, shadowspawn commented on tests/options.bool.test.js
> +  test('when bypassing negatable then value is true', () => {
```suggestion
  test('when override negatable and flag specified then value is true', () => {
```

2024-08-30 05:39 UTC, shadowspawn requested changes
I would like a couple more tests, but I can add these myself later if you prefer.

I would like a test that when the overridden flag is not specified that the option value is undefined rather than true.

And an explicit test, although redundant, that the name of the stored option is just camel case. So see `noCheese` in options and `cheese' is undefined. This one is implicitly tested already, but since it is a key change I would like an explicit test covering this particular behaviour.

2024-08-30 10:47 UTC, bernard-wagner commented
> I would like a couple more tests, but I can add these myself later if you prefer.
> 
> I would like a test that when the overridden flag is not specified that the option value is undefined rather than true.
> 
> And an explicit test, although redundant, that the name of the stored option is just camel case. So see `noCheese` in options and `cheese' is undefined. This one is implicitly tested already, but since it is a key change I would like an explicit test covering this particular behaviour.

I think the tests cover all the permutations now.

2024-08-30 22:48 UTC, shadowspawn commented
Thanks for all the tests for a small code change! I did need to search the code a couple of times to check the one-liner was really going to work, so the tests are good for confirming and also catching future regressions.

One more variation. You added this:

```
  test('when negatable boolean flag is specified and negate is overridden then positive value is undefined', () => {
```

And I would also like this variation, to check the default is not getting set. This is implicitly tested by the above, but the default value being true for a negated boolean is a feature of the standard behaviour and I want to check it does not occur.)

```
  test('when negatable boolean flag is unspecified and negate is overridden then positive value is undefined', () => {
```

2024-08-30 22:50 UTC, shadowspawn approved these changes
One  more test suggested, but not needed for approval.

2024-08-31 06:45 UTC, shadowspawn commented
(Thanks for the work on the extra tests @bernard-wagner )

2024-09-08 01:43 UTC, shadowspawn commented
I am having second thoughts about this @abetomo

Basically, I don't want to commit to supporting bypassing negation as a feature, like by adding a chaining method on `Option` to clear `negate`. So I don't really want to add all the tests showing we support it (although they were good for showing it does work currently).

Two possible approaches for your consideration:
1) we could just change `attributeName` implementation as in this PR and not add any tests. So it would make it easier to bypass negation without us officially supporting this as a use case. And I think the change is reasonable on its own, makes the code a little clearer.
2) we could add an example file showing subclassing `Option` to allow bypassing negation, including a chaining method. (With a note that it isn't officially supported.)

2024-09-08 01:55 UTC, abetomo commented
I too think the 1 approach is better.

2024-09-13 23:30 UTC, shadowspawn commented
Closing in favour of #2250 which has just the code change and not the tests.

Thanks for the suggestion @bernard-wagner and work on the tests.

2024-09-13 23:30 UTC, closed without merging